import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const OUT='C:/Users/ADMIN/Documents/Codex/healthlink-sentinel/HealthLink-Sentinel-Pitch-Startup-2026-v2.pptx';
const TMP='C:/Users/ADMIN/Documents/Codex/healthlink-sentinel/.tmp/deck-startup-2026';
const W=1280,H=720;
const C={bg:'#080b13',ink:'#f7f9fc',muted:'#a4adbd',soft:'#151a27',line:'#30394b',lime:'#b6f36b',cyan:'#65e7e0',orange:'#ffb454',pink:'#ff6d91',purple:'#9a8cff'};
const p=Presentation.create({slideSize:{width:W,height:H}});
const imgCentro=await fs.readFile('C:/Users/ADMIN/Documents/Codex/healthlink-sentinel/.tmp/deck-healthlink/real-centro-wide.png');
const imgAlertas=await fs.readFile('C:/Users/ADMIN/Documents/Codex/healthlink-sentinel/.tmp/deck-healthlink/real-alertas-wide.png');
const imgUnidades=await fs.readFile('C:/Users/ADMIN/Documents/Codex/healthlink-sentinel/.tmp/deck-healthlink/real-unidades-wide.png');
function sh(s,g,pos,fill='none',stroke='none',r='rounded-xl'){const o={geometry:g,position:pos,fill,line:stroke==='none'?{style:'solid',fill:'none',width:0}:{style:'solid',fill:stroke,width:1}};if(['rect','textbox','roundRect'].includes(g))o.borderRadius=r;return s.shapes.add(o)}
function t(s,text,x,y,w,h,size=20,color=C.ink,bold=false){const q=sh(s,'textbox',{left:x,top:y,width:w,height:h});q.text=text;q.text.style={fontSize:size,color,bold,fontFace:'Aptos'};return q}
function ln(s,x1,y1,x2,y2,color=C.line,width=2){return s.shapes.add({geometry:'line',position:{left:x1,top:y1,width:x2-x1,height:y2-y1},line:{style:'solid',fill:color,width}})}
function dot(s,x,y,color){sh(s,'ellipse',{left:x,top:y,width:14,height:14},color)}
function img(s,b,x,y,w,h,alt){s.images.add({blob:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),contentType:'image/png',alt,fit:'cover',position:{left:x,top:y,width:w,height:h},geometry:'roundRect',borderRadius:'rounded-xl'})}
function chrome(s,n,tag){t(s,String(n).padStart(2,'0'),1160,670,48,20,12,C.muted,true);t(s,'HEALTHLINK SENTINEL  /  PITCH 2026',72,670,500,20,12,C.muted,true)}
function title(s,k,h,sub=''){t(s,k.toUpperCase(),72,48,700,22,13,C.lime,true);t(s,h,72,88,1120,76,36,C.ink,true);if(sub)t(s,sub,72,174,1110,34,18,C.muted)}
function pill(s,text,x,y,w,color=C.lime){sh(s,'roundRect',{left:x,top:y,width:w,height:32},color,'none','rounded-full');t(s,text,x+14,y+7,w-28,18,13,C.bg,true)}
function card(s,x,y,w,h,head,body,color=C.lime){sh(s,'roundRect',{left:x,top:y,width:w,height:h},C.soft,C.line);dot(s,x+24,y+24,color);t(s,head,x+50,y+18,w-68,28,21,C.ink,true);t(s,body,x+24,y+64,w-48,h-78,16,C.muted)}
function notes(s,text){try{if(s.notes)s.notes.text='[Sources]\n'+text}catch{}}

// 1
{const s=p.slides.add();s.background.fill=C.bg;sh(s,'rect',{left:0,top:0,width:W,height:H},C.bg);sh(s,'rect',{left:0,top:0,width:22,height:H},C.lime);t(s,'HEALTHLINK',72,84,620,64,52,C.ink,true);t(s,'SENTINEL',72,146,620,64,52,C.lime,true);t(s,'A operação de conectividade das unidades móveis\nprecisa ser tão inteligente quanto a missão.',76,255,730,84,28,C.ink,true);pill(s,'PITCH DE PRODUTO',76,390,165,C.lime);t(s,'Monitoramento operacional + gestão de links + suporte em uma única camada.',76,450,650,44,20,C.muted);sh(s,'roundRect',{left:850,top:96,width:300,height:420},C.soft,C.line);t(s,'A TESE',890,132,140,22,14,C.lime,true);t(s,'Zabbix\ncoleta.\nHealthLink\ninterpreta\ne age.',890,190,210,230,36,C.ink,true);t(s,'Apresentação para decisão',76,620,400,24,15,C.muted);notes(s,'Fonte: PRD oficial HealthLink Sentinel; estado atual do projeto.');}
// 2
{const s=p.slides.add();s.background.fill=C.bg;title(s,'O problema','Quando uma unidade móvel para, o custo aparece antes do alerta.','O time precisa descobrir rápido: qual unidade, qual link, qual causa e qual ação.');
const items=[['Dado demais','Hosts, itens, triggers e eventos em camadas técnicas.'],['Contexto de menos','O alerta não nasce com unidade, missão, rota e impacto.'],['Ação fragmentada','Diagnóstico, inventário e suporte vivem em fluxos separados.']];items.forEach((v,i)=>card(s,72+i*382,270,340,180,v[0],v[1],[C.pink,C.orange,C.purple][i]));t(s,'A oportunidade: transformar telemetria em decisão operacional.',72,535,1000,44,26,C.lime,true);chrome(s,2,'Problema');notes(s,'Fonte: PRD 01-VISAO-PRODUTO; PRD 04-UX-FLUXOS; interpretação do problema operacional a partir do produto.');}
// 3
{const s=p.slides.add();s.background.fill=C.bg;title(s,'A solução','Uma camada operacional construída sobre o investimento que já existe.','O Zabbix continua coletando. O HealthLink conecta dados, pessoas e ações.');ln(s,290,360,480,360,C.cyan,4);ln(s,800,360,970,360,C.lime,4);sh(s,'roundRect',{left:72,top:285,width:218,height:150},C.soft,C.line);t(s,'FONTES',104,320,140,22,14,C.muted,true);t(s,'Zabbix\nStarlink\nMikroTik',104,355,160,82,24,C.ink,true);sh(s,'roundRect',{left:480,top:250,width:320,height:220},C.lime,'none');t(s,'HEALTHLINK\nSENTINEL',532,300,230,68,30,C.bg,true);t(s,'normaliza • correlaciona\nprojeta • audita • orienta',532,390,240,48,16,C.bg,true);sh(s,'roundRect',{left:970,top:285,width:238,height:150},C.soft,C.line);t(s,'RESULTADO',1000,320,150,22,14,C.muted,true);t(s,'NOC\nSuporte\nGestão',1000,355,170,82,24,C.ink,true);chrome(s,3,'Solução');notes(s,'Fonte: PRD ZABBIX-API; PRD 02-ARQUITETURA-SISTEMA; ADR-001.');}
// 4
{const s=p.slides.add();s.background.fill=C.bg;title(s,'O produto','Dois módulos, uma visão de operação.','A arquitetura atende tanto a infraestrutura corporativa quanto a conectividade em campo.');card(s,72,260,520,250,'01  Infraestrutura','NOC, mapa, filtros por tipo/situação/UF, alertas, inventário, relatórios, RBAC, auditoria e histórico.',C.cyan);card(s,688,260,520,250,'02  Unidades móveis','Links, Starlink, agente local, localização, cobertura/obstrução, diagnóstico e saúde do coletor.',C.orange);t(s,'Um produto com dois pontos de entrada para o mesmo objetivo: manter a missão operacional.',72,560,1120,40,23,C.ink,true);chrome(s,4,'Produto');notes(s,'Fonte: PRD MODULOS; Estado Atual 2026-08-24; Plano de Coleta Starlink e Unidade Movel.');}
// 5
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Módulo 01','Infraestrutura que fala a linguagem do negócio.','A equipe não precisa mais começar pelo host: começa pela unidade e pelo impacto.');img(s,imgCentro,72,250,560,315,'Centro Operacional real');card(s,680,250,528,115,'Mapa operacional','Brasil, UF, unidade e pior estado consolidado entre equipamentos.',C.cyan);card(s,680,385,528,115,'Alertas e relatórios','Incidentes ativos/resolvidos, severidade, reconhecimento, tempo médio e impressão.',C.pink);card(s,680,520,528,115,'Governança','RBAC, isolamento por cliente, auditoria e histórico preservado.',C.purple);chrome(s,5,'Módulo 01');notes(s,'Fonte: captura real do Centro Operacional; PRD MODULOS; estado atual 2026-08-24.');}
// 6
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Módulo 02','Unidades móveis com um agente dentro da rede.','A operação central enxerga a unidade sem precisar acessar diretamente a antena ou o MikroTik.');img(s,imgUnidades,72,255,560,315,'Unidades móveis real');card(s,680,255,528,115,'Agente local','Heartbeat, versão, última coleta, fila local, retry e atualização por SHA-256.',C.lime);card(s,680,390,528,115,'Starlink + MikroTik','Telemetria específica da antena, caminho WAN e interfaces sem misturar fontes.',C.orange);card(s,680,525,528,115,'Suporte orientado','Ping, tracert, origem da métrica e evidência para o atendimento.',C.cyan);chrome(s,6,'Módulo 02');notes(s,'Fonte: captura real de Unidades Móveis; apps/agent; Plano de Coleta Starlink e Unidade Movel; Estado Atual 2026-08-24.');}
// 7
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Integração Starlink','A antena deixa de ser uma caixa-preta.','O HealthLink transforma sinais específicos da constelação em informação operacional.');const vals=[['Visibilidade','Latência, perda, download, upload e uptime.',C.cyan],['Condição','Disponibilidade/cobertura, obstrução, SNR e temperatura.',C.orange],['Localização','Latitude/longitude da antena e associação à unidade.',C.lime],['Confiabilidade','Fonte, idade da amostra, N/D e estado unknown quando stale.',C.pink]];vals.forEach((v,i)=>card(s,72+(i%2)*570,260+Math.floor(i/2)*165,520,130,v[0],v[1],v[2]));t(s,'Já validado: agente autenticou, coletou métricas reais e enviou lote à API com fila pendente zerada.',72,610,1120,30,18,C.lime,true);chrome(s,7,'Starlink');notes(s,'Fonte: Módulo Starlink - Estratégia Híbrida; validação real de 17/08/2026; apps/agent/src.');}
// 8
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Funcionalidades novas','O produto já saiu do conceito e ganhou operação real.','As entregas recentes aumentam capacidade, escala e evidência de execução.');const f=[['Filtros operacionais','Tipo de unidade, situação e UF alimentam indicadores, mapa e visão.',C.cyan],['Relatórios de incidentes','Filtros, indicadores, tabela auditável, atualização e impressão.',C.lime],['Visão de agentes','Agente em execução, parado, sem vínculo, versão e última coleta.',C.orange],['Repositório do agente','Publicação Windows/Linux, SHA-256, versão patch e download autenticado.',C.purple],['Provisionamento','Gerar agente por unidade/servidor, enrollment e fonte Starlink local.',C.pink],['Histórico e retenção','Estados preservados, telemetria stale controlada e limpeza por política.',C.cyan]];f.forEach((v,i)=>card(s,72+(i%3)*382,250+Math.floor(i/3)*170,340,135,v[0],v[1],v[2]));chrome(s,8,'Progresso');notes(s,'Fonte: handoff e Estado Atual atualizados em 2026-08-24; implementação real do projeto.');}
// 9
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Diferencial','O Zabbix mostra o evento. O HealthLink fecha o ciclo operacional.','A proposta não é substituir o Zabbix: é capturar o valor que fica depois da coleta.');const rows=[['Contexto','Host / trigger','Unidade / impacto / missão'],['Experiência','Tela técnica','Mapa / detalhe / alerta / relatório'],['Suporte','Leitura manual','Diagnóstico e evidência no mesmo fluxo'],['Governança','Configuração espalhada','RBAC / multi-tenant / auditoria'],['Escala','Agente por unidade','Repositório / provisionamento / versões']];t(s,'ZABBIX',250,225,200,24,14,C.muted,true);t(s,'HEALTHLINK SENTINEL',760,225,300,24,14,C.lime,true);ln(s,72,260,1208,260,C.line,2);rows.forEach((r,i)=>{const y=280+i*65;t(s,r[0],72,y,150,28,19,C.ink,true);t(s,r[1],250,y,390,28,18,C.muted);t(s,r[2],760,y,430,28,18,C.ink,true);ln(s,72,y+42,1208,y+42,C.line,1)});t(s,'O diferencial está na última milha: da informação técnica para a decisão.',72,610,1100,30,22,C.lime,true);chrome(s,9,'Diferencial');notes(s,'Fonte: PRD ZABBIX-API; estado atual do projeto; interpretação comparativa do posicionamento.');}
// 10
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Segurança e governança','Escalar sem perder controle.','A plataforma foi pensada para operar dados críticos com limites claros.');card(s,72,270,260,220,'RBAC','Cada perfil acessa e executa apenas o necessário.',C.cyan);card(s,362,270,260,220,'Multi-tenant','Clientes e operações isolados por tenant e RLS.',C.lime);card(s,652,270,260,220,'Auditoria','Ações, vínculos, alterações e comandos deixam evidência.',C.orange);card(s,942,270,266,220,'Histórico','Incidentes, estados e telemetria preservam contexto.',C.pink);t(s,'Segurança não é uma camada posterior: é parte do produto desde o MVP.',72,565,1100,38,23,C.ink,true);chrome(s,10,'Governança');notes(s,'Fonte: ADR-001; PRD USUARIOS-RBAC; Estado Atual.');}
// 11
{const s=p.slides.add();s.background.fill=C.bg;title(s,'Roadmap','A próxima vantagem é agir — com segurança e escala.','A evolução segue o valor operacional, não uma lista de features desconectadas.');const phases=[['Agora','Homologar agente como serviço Windows/Linux; coleta contínua, reinício e rollback.',C.cyan],['Próximo','Comandos remotos autorizados: reiniciar, ajustar Wi‑Fi e aplicar configurações Starlink.',C.orange],['Escala','Políticas por grupo, atualização remota, SLA, multi-clientes e integrações.',C.lime],['Futuro','IA operacional, previsão de degradação, recomendações e canais WhatsApp/Telegram.',C.purple]];phases.forEach((v,i)=>{const x=72+i*285;dot(s,x,300,v[2]);t(s,v[0].toUpperCase(),x+28,290,180,20,13,v[2],true);t(s,v[1],x,350,230,130,19,C.ink,true);if(i<3)ln(s,x+235,306,x+270,306,C.line,2)});t(s,'Cada etapa precisa reduzir tempo de diagnóstico, manter rastreabilidade e ampliar a capacidade de atendimento.',72,570,1100,42,20,C.muted);chrome(s,11,'Roadmap');notes(s,'Fonte: PRD ROADMAP; tarefas de homologação do agente; Plano de Coleta Starlink e Unidade Movel. Roadmap futuro apresentado como proposta.');}
// 12
{const s=p.slides.add();s.background.fill=C.bg;sh(s,'rect',{left:0,top:0,width:W,height:H},C.bg);sh(s,'rect',{left:0,top:0,width:W,height:18},C.lime);t(s,'POR QUE AGORA?',72,95,400,24,14,C.lime,true);t(s,'Porque já existe produto,\nintegração e caminho de escala.',72,145,900,120,45,C.ink,true);t(s,'A próxima decisão não é “se é pertinente”.\nÉ onde validar primeiro.',76,335,720,70,25,C.muted);pill(s,'PILOTO CONTROLADO',76,470,190,C.lime);t(s,'Selecionar unidades móveis, medir tempo de diagnóstico e validar a operação de ponta a ponta.',76,530,760,45,22,C.ink,true);t(s,'HEALTHLINK\nSENTINEL',930,510,230,80,30,C.lime,true);chrome(s,12,'Fechamento');notes(s,'Fonte: síntese do PRD, estado atual e roadmap do projeto.');}

for(const [i,s] of p.slides.items.entries()){const b=await p.export({slide:s,format:'png',scale:1});await fs.writeFile(`${TMP}/rendered/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
const m=await p.export({format:'webp',montage:true,scale:1});await fs.writeFile(`${TMP}/montage.webp`,new Uint8Array(await m.arrayBuffer()));
const file=await PresentationFile.exportPptx(p);await file.save(OUT);console.log(OUT);
